use crate::{
    time::GameTime,
    weather::{Weather, WeatherType},
};

pub enum AreaName {
    LimsaLominsa,
    MiddleLaNoscea,
    LowerLaNoscea,
    EasternLaNoscea,
    WesternLaNoscea,
    UpperLaNoscea,
    OuterLaNoscea,
    WolvesDenPier,
    Gridania,
    CentralShroud,
    EastShroud,
    SouthShroud,
    NorthShroud,
    Uldah,
    WesternThanalan,
    CentralThanalan,
    EasternThanalan,
    SouthernThanalan,
    NorthernThanalan,
    Ishgard,
    CoerthasCentralHighlands,
    CoerthasWesternHighlands,
    TheSeaOfClouds,
    AzysLla,
    Idyllshire,
    TheDravanianForelands,
    TheDravanianHinterlands,
    TheChurningMists,
    RhalgrsReach,
    TheFringes,
    ThePeaks,
    TheLochs,
    Kugane,
    TheRubySea,
    Yanxia,
    TheAzimSteppe,
    TheCrystarium,
    Eulmore,
    Lakeland,
    Kholusia,
    AmhAraeng,
    IlMheg,
    TheRaktikaGreatwood,
    TheTempest,
    Mist,
    TheLavenderBeds,
    TheGoblet,
    Shirogane,
    MorDhona,
    BozjanSouthernFront,
    Zadnor,
    EurekaAnemos,
    EurekaPagos,
    EurekaPyros,
    EurekaHydatos,
    TheDiadem,
}

pub struct Area {
    name: AreaName,
}

impl Area {
    pub fn weather(&self, game_time: GameTime) -> WeatherType {
        let n = Weather::from_game_time(game_time);
        match self.name {
            AreaName::AmhAraeng => match n {
                n if n < 45 => WeatherType::FairSkies,
                n if n < 60 => WeatherType::Clouds,
                n if n < 70 => WeatherType::DustStorms,
                n if n < 80 => WeatherType::HeatWaves,
                _ => WeatherType::ClearSkies,
            },
            AreaName::AzysLla => match n {
                n if n < 35 => WeatherType::FairSkies,
                n if n < 70 => WeatherType::Clouds,
                _ => WeatherType::Thunder,
            },
            AreaName::BozjanSouthernFront => match n {
                n if n < 52 => WeatherType::FairSkies,
                n if n < 64 => WeatherType::Rain,
                n if n < 76 => WeatherType::Wind,
                n if n < 88 => WeatherType::Thunder,
                _ => WeatherType::DustStorms,
            },
            AreaName::CentralShroud => match n {
                n if n < 5 => WeatherType::Thunder,
                n if n < 20 => WeatherType::Rain,
                n if n < 30 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 55 => WeatherType::FairSkies,
                n if n < 85 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::CentralThanalan => match n {
                n if n < 15 => WeatherType::DustStorms,
                n if n < 55 => WeatherType::ClearSkies,
                n if n < 75 => WeatherType::FairSkies,
                n if n < 85 => WeatherType::Clouds,
                n if n < 95 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::CoerthasCentralHighlands => match n {
                n if n < 20 => WeatherType::Blizzards,
                n if n < 60 => WeatherType::Snow,
                n if n < 70 => WeatherType::FairSkies,
                n if n < 75 => WeatherType::ClearSkies,
                n if n < 90 => WeatherType::Clouds,
                _ => WeatherType::Fog,
            },
            AreaName::CoerthasWesternHighlands => match n {
                n if n < 20 => WeatherType::Blizzards,
                n if n < 60 => WeatherType::Snow,
                n if n < 70 => WeatherType::FairSkies,
                n if n < 75 => WeatherType::ClearSkies,
                n if n < 90 => WeatherType::Clouds,
                _ => WeatherType::Fog,
            },
            AreaName::EastShroud => match n {
                n if n < 5 => WeatherType::Thunder,
                n if n < 20 => WeatherType::Rain,
                n if n < 30 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 55 => WeatherType::FairSkies,
                n if n < 85 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::EasternLaNoscea => match n {
                n if n < 5 => WeatherType::Fog,
                n if n < 50 => WeatherType::ClearSkies,
                n if n < 80 => WeatherType::FairSkies,
                n if n < 90 => WeatherType::Clouds,
                n if n < 95 => WeatherType::Rain,
                _ => WeatherType::Showers,
            },
            AreaName::EasternThanalan => match n {
                n if n < 40 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 70 => WeatherType::Clouds,
                n if n < 80 => WeatherType::Fog,
                n if n < 85 => WeatherType::Rain,
                _ => WeatherType::Showers,
            },
            AreaName::Eulmore => match n {
                n if n < 10 => WeatherType::Gales,
                n if n < 20 => WeatherType::Rain,
                n if n < 30 => WeatherType::Fog,
                n if n < 45 => WeatherType::Clouds,
                n if n < 85 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::EurekaAnemos => match n {
                n if n < 30 => WeatherType::FairSkies,
                n if n < 60 => WeatherType::Gales,
                n if n < 90 => WeatherType::Showers,
                _ => WeatherType::Snow,
            },
            AreaName::EurekaHydatos => match n {
                n if n < 12 => WeatherType::FairSkies,
                n if n < 34 => WeatherType::Showers,
                n if n < 56 => WeatherType::Gloom,
                n if n < 78 => WeatherType::Thunderstorms,
                _ => WeatherType::Snow,
            },
            AreaName::EurekaPagos => match n {
                n if n < 10 => WeatherType::FairSkies,
                n if n < 28 => WeatherType::Fog,
                n if n < 46 => WeatherType::HeatWaves,
                n if n < 64 => WeatherType::Snow,
                n if n < 82 => WeatherType::Thunder,
                _ => WeatherType::Blizzards,
            },
            AreaName::EurekaPyros => match n {
                n if n < 10 => WeatherType::FairSkies,
                n if n < 28 => WeatherType::HeatWaves,
                n if n < 46 => WeatherType::Thunder,
                n if n < 64 => WeatherType::Blizzards,
                n if n < 82 => WeatherType::UmbralWind,
                _ => WeatherType::Snow,
            },
            AreaName::Gridania => match n {
                n if n < 5 => WeatherType::Rain,
                n if n < 20 => WeatherType::Rain,
                n if n < 30 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 55 => WeatherType::FairSkies,
                n if n < 85 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::Idyllshire => match n {
                n if n < 10 => WeatherType::Clouds,
                n if n < 20 => WeatherType::Fog,
                n if n < 30 => WeatherType::Rain,
                n if n < 40 => WeatherType::Showers,
                n if n < 70 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::IlMheg => match n {
                n if n < 10 => WeatherType::Rain,
                n if n < 20 => WeatherType::Fog,
                n if n < 35 => WeatherType::Clouds,
                n if n < 45 => WeatherType::Thunderstorms,
                n if n < 60 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::Ishgard => match n {
                n if n < 60 => WeatherType::Snow,
                n if n < 70 => WeatherType::FairSkies,
                n if n < 75 => WeatherType::ClearSkies,
                n if n < 90 => WeatherType::Clouds,
                _ => WeatherType::Fog,
            },
            AreaName::Kholusia => match n {
                n if n < 10 => WeatherType::Gales,
                n if n < 20 => WeatherType::Rain,
                n if n < 30 => WeatherType::Fog,
                n if n < 45 => WeatherType::Clouds,
                n if n < 85 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::Kugane => match n {
                n if n < 10 => WeatherType::Rain,
                n if n < 20 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 80 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::Lakeland => match n {
                n if n < 20 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 75 => WeatherType::Clouds,
                n if n < 85 => WeatherType::Fog,
                n if n < 95 => WeatherType::Rain,
                _ => WeatherType::Thunderstorms,
            },
            AreaName::LimsaLominsa => match n {
                n if n < 20 => WeatherType::Clouds,
                n if n < 50 => WeatherType::ClearSkies,
                n if n < 80 => WeatherType::FairSkies,
                n if n < 90 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::LowerLaNoscea => match n {
                n if n < 20 => WeatherType::Clouds,
                n if n < 50 => WeatherType::ClearSkies,
                n if n < 70 => WeatherType::FairSkies,
                n if n < 80 => WeatherType::Wind,
                n if n < 90 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::MiddleLaNoscea => match n {
                n if n < 20 => WeatherType::Clouds,
                n if n < 50 => WeatherType::ClearSkies,
                n if n < 70 => WeatherType::FairSkies,
                n if n < 80 => WeatherType::Wind,
                n if n < 90 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::Mist => match n {
                n if n < 20 => WeatherType::Clouds,
                n if n < 50 => WeatherType::ClearSkies,
                n if n < 70 => WeatherType::FairSkies,
                n if n < 80 => WeatherType::FairSkies,
                n if n < 90 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::MorDhona => match n {
                n if n < 15 => WeatherType::Clouds,
                n if n < 30 => WeatherType::Fog,
                n if n < 60 => WeatherType::Gloom,
                n if n < 75 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::NorthShroud => match n {
                n if n < 5 => WeatherType::Fog,
                n if n < 10 => WeatherType::Showers,
                n if n < 25 => WeatherType::Rain,
                n if n < 30 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 70 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::NorthernThanalan => match n {
                n if n < 5 => WeatherType::ClearSkies,
                n if n < 20 => WeatherType::FairSkies,
                n if n < 50 => WeatherType::Clouds,
                _ => WeatherType::Fog,
            },
            AreaName::OuterLaNoscea => match n {
                n if n < 30 => WeatherType::ClearSkies,
                n if n < 50 => WeatherType::FairSkies,
                n if n < 70 => WeatherType::Clouds,
                n if n < 85 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::RhalgrsReach => match n {
                n if n < 15 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 80 => WeatherType::Clouds,
                n if n < 90 => WeatherType::Fog,
                _ => WeatherType::Thunder,
            },
            AreaName::Shirogane => match n {
                n if n < 10 => WeatherType::Rain,
                n if n < 20 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 80 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::SouthShroud => match n {
                n if n < 5 => WeatherType::Fog,
                n if n < 10 => WeatherType::Thunderstorms,
                n if n < 25 => WeatherType::Thunder,
                n if n < 30 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 70 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::SouthernThanalan => match n {
                n if n < 20 => WeatherType::HeatWaves,
                n if n < 60 => WeatherType::ClearSkies,
                n if n < 80 => WeatherType::FairSkies,
                n if n < 90 => WeatherType::Clouds,
                _ => WeatherType::Fog,
            },
            AreaName::TheAzimSteppe => match n {
                n if n < 5 => WeatherType::Gales,
                n if n < 10 => WeatherType::Wind,
                n if n < 17 => WeatherType::Rain,
                n if n < 25 => WeatherType::Fog,
                n if n < 35 => WeatherType::Clouds,
                n if n < 75 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::TheChurningMists => match n {
                n if n < 10 => WeatherType::Clouds,
                n if n < 20 => WeatherType::Gales,
                n if n < 40 => WeatherType::UmbralStatic,
                n if n < 70 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::TheCrystarium => match n {
                n if n < 20 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 75 => WeatherType::Clouds,
                n if n < 85 => WeatherType::Fog,
                n if n < 95 => WeatherType::Rain,
                _ => WeatherType::Thunderstorms,
            },
            AreaName::TheDiadem => match n {
                n if n < 30 => WeatherType::FairSkies,
                n if n < 60 => WeatherType::Fog,
                n if n < 90 => WeatherType::Wind,
                _ => WeatherType::UmbralWind,
            },
            AreaName::TheDravanianForelands => match n {
                n if n < 10 => WeatherType::Clouds,
                n if n < 20 => WeatherType::Fog,
                n if n < 30 => WeatherType::Thunder,
                n if n < 40 => WeatherType::DustStorms,
                n if n < 70 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::TheDravanianHinterlands => match n {
                n if n < 10 => WeatherType::Clouds,
                n if n < 20 => WeatherType::Fog,
                n if n < 30 => WeatherType::Rain,
                n if n < 40 => WeatherType::Showers,
                n if n < 70 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::TheFringes => match n {
                n if n < 15 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 80 => WeatherType::Clouds,
                n if n < 90 => WeatherType::Fog,
                _ => WeatherType::Thunder,
            },
            AreaName::TheGoblet => match n {
                n if n < 40 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 85 => WeatherType::Clouds,
                n if n < 95 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::TheLavenderBeds => match n {
                n if n < 5 => WeatherType::Clouds,
                n if n < 20 => WeatherType::Rain,
                n if n < 30 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 55 => WeatherType::FairSkies,
                n if n < 85 => WeatherType::ClearSkies,
                _ => WeatherType::FairSkies,
            },
            AreaName::TheLochs => match n {
                n if n < 20 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 80 => WeatherType::Clouds,
                n if n < 90 => WeatherType::Fog,
                _ => WeatherType::Thunderstorms,
            },
            AreaName::ThePeaks => match n {
                n if n < 10 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 75 => WeatherType::Clouds,
                n if n < 85 => WeatherType::Fog,
                n if n < 95 => WeatherType::Wind,
                _ => WeatherType::DustStorms,
            },
            AreaName::TheRaktikaGreatwood => match n {
                n if n < 10 => WeatherType::Fog,
                n if n < 20 => WeatherType::Rain,
                n if n < 30 => WeatherType::UmbralWind,
                n if n < 45 => WeatherType::ClearSkies,
                n if n < 85 => WeatherType::FairSkies,
                _ => WeatherType::Clouds,
            },
            AreaName::TheRubySea => match n {
                n if n < 10 => WeatherType::Thunder,
                n if n < 20 => WeatherType::Wind,
                n if n < 35 => WeatherType::Clouds,
                n if n < 75 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::TheSeaOfClouds => match n {
                n if n < 30 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 70 => WeatherType::Clouds,
                n if n < 80 => WeatherType::Fog,
                n if n < 90 => WeatherType::Wind,
                _ => WeatherType::UmbralWind,
            },
            AreaName::TheTempest => match n {
                n if n < 20 => WeatherType::Clouds,
                n if n < 80 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::Uldah => match n {
                n if n < 40 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 85 => WeatherType::Clouds,
                n if n < 95 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::UpperLaNoscea => match n {
                n if n < 30 => WeatherType::ClearSkies,
                n if n < 50 => WeatherType::FairSkies,
                n if n < 70 => WeatherType::Clouds,
                n if n < 80 => WeatherType::Fog,
                n if n < 90 => WeatherType::Thunder,
                _ => WeatherType::Thunderstorms,
            },
            AreaName::WesternLaNoscea => match n {
                n if n < 10 => WeatherType::Fog,
                n if n < 40 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 80 => WeatherType::Clouds,
                n if n < 90 => WeatherType::Wind,
                _ => WeatherType::Gales,
            },
            AreaName::WesternThanalan => match n {
                n if n < 40 => WeatherType::ClearSkies,
                n if n < 60 => WeatherType::FairSkies,
                n if n < 85 => WeatherType::Clouds,
                n if n < 95 => WeatherType::Fog,
                _ => WeatherType::Rain,
            },
            AreaName::WolvesDenPier => match n {
                n if n < 20 => WeatherType::Clouds,
                n if n < 50 => WeatherType::ClearSkies,
                n if n < 80 => WeatherType::FairSkies,
                n if n < 90 => WeatherType::Fog,
                _ => WeatherType::Thunderstorms,
            },
            AreaName::Yanxia => match n {
                n if n < 5 => WeatherType::Showers,
                n if n < 15 => WeatherType::Rain,
                n if n < 25 => WeatherType::Fog,
                n if n < 40 => WeatherType::Clouds,
                n if n < 80 => WeatherType::FairSkies,
                _ => WeatherType::ClearSkies,
            },
            AreaName::Zadnor => match n {
                n if n < 60 => WeatherType::FairSkies,
                n if n < 70 => WeatherType::Rain,
                n if n < 80 => WeatherType::Wind,
                n if n < 90 => WeatherType::Thunder,
                _ => WeatherType::Snow,
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{Area, AreaName};
    use crate::{time::GameTime, weather::WeatherType};
    use chrono::prelude::*;

    #[test]
    fn it_finds_the_weather_for_an_area() {
        let time = Utc.ymd(2022, 3, 13).and_hms(0, 0, 0);
        let game_time = GameTime::from_date_time(time);
        let area = Area {
            name: AreaName::LimsaLominsa,
        };
        assert_eq!(area.weather(game_time), WeatherType::Clouds);
    }

    #[test]
    fn it_finds_the_weather_for_an_area_when_the_time_is_different() {
        let time = Utc.ymd(2022, 3, 13).and_hms(2, 50, 0);
        let game_time = GameTime::from_date_time(time);
        let area = Area {
            name: AreaName::LimsaLominsa,
        };
        assert_eq!(area.weather(game_time), WeatherType::Fog);
    }
}
